spring:
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:C:/web/apt_project
        - file:/home/ubuntu/apt_project/data
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  application:
    name: examJun
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ls-6a6167099f1b8b918a180513a70146a343e9ff7c.cps8so0e8jyp.ap-northeast-2.rds.amazonaws.com:3306/examJun?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dbmasteruser
    password: '85-j;#!!8vag<Qo2KSm4gF{6:x#wK+$u'